version: 2.1

orbs:
  architect: giantswarm/architect@0.13.0

jobs:
  debug-tag:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: |
          echo "running for tag ${CIRCLE_TAG}"

  update-krew-index:
    docker:
      - image: circleci/golang:1.13

    environment:
      KREW_RELEASE_BOT_VERSION: v0.0.38
      GITHUB_ACTIONS: true
      GITHUB_REPOSITORY: giantswarm/kubectl-gs
      GITHUB_ACTOR: architectbot

    steps:
      - checkout
      - run: |
          echo "using krew-release-bot version ${KREW_RELEASE_BOT_VERSION}"
          curl -LO https://github.com/rajatjindal/krew-release-bot/releases/download/${KREW_RELEASE_BOT_VERSION}/krew-release-bot_${KREW_RELEASE_BOT_VERSION}_linux_amd64.tar.gz
          tar -xvf krew-release-bot_${KREW_RELEASE_BOT_VERSION}_linux_amd64.tar.gz
          echo export GITHUB_REF=refs/tags/${CIRCLE_TAG} >> "$BASH_ENV"
          echo export GITHUB_WORKSPACE=$(pwd) >> "$BASH_ENV"
      - run: ./krew-release-bot action


workflows:
  go-build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: kubectl-gs
          filters:
            tags:
              only: /^v.*/
  update-krew:
    jobs:
      - debug-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - request-manual-approval:
          type: approval
          requires:
            - debug-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - update-krew-index:
          requires:
            - debug-tag
            - request-manual-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
