# Testing windows code signing
#
name: windows

on: [pull_request]

jobs:
  windows:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GO_VERSION: 1.17.8
      ARTIFACT_DIR: bin-dist
      TAG: 11.22.33
      CODE_SIGNING_CERT_BUNDLE_BASE64: ${{ secrets.CODE_SIGNING_CERT_BUNDLE_BASE64 }}
      CODE_SIGNING_CERT_BUNDLE_PASSWORD: ${{ secrets.CODE_SIGNING_CERT_BUNDLE_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Show make version
      run: make --version
    - name: Show path
      run: pwd
    - name: Trying to build a windows binary
      run: make package-windows-amd64
